#!/bin/bash

###

src_root='/path/to/cdi'

name='cdi'
version='1.8.4'

###

set -eu
set -o pipefail

script_dir=$(cd "$(dirname "$0")"; pwd)
root_dir=$(cd "${script_dir}/../.."; pwd)
output_dir="${root_dir}/${name}/${version}"

FPP='gfortran -E -cpp'
FPP_FLAGS=

OMNI='F_Front'
OMNI_FLAGS="-M ${output_dir}"

files='
mo_cdi.f90
'

mkdir -p "${output_dir}"
cd "${src_root}/src"

for file in ${files}; do
	${FPP} ${FPP_FLAGS} ${file} | ${OMNI} ${OMNI_FLAGS} >/dev/null
done
