#!/bin/bash

###

src_root='/path/to/mtime'

name='mtime'
version='1.0.11-rc2'

###

set -eu
set -o pipefail

script_dir=$(cd "$(dirname "$0")"; pwd)
root_dir=$(cd "${script_dir}/../.."; pwd)
output_dir="${root_dir}/${name}/${version}"

FPP='gfortran -E -cpp'
FPP_FLAGS=

OMNI='F_Front'
OMNI_FLAGS="-M ${output_dir}"

files='
mtime_constants.f90
mtime_error_handling.f90
mtime_c_bindings.f90
libmtime.f90
libmtime_hl.f90
'

mkdir -p "${output_dir}"
cd "${src_root}/src"

for file in ${files}; do
	${FPP} ${FPP_FLAGS} ${file} | ${OMNI} ${OMNI_FLAGS} >/dev/null
done
