#!/bin/bash

###

sct_dir='/path/to/sct'
sct_ver='1.0'

###

set -eu
set -o pipefail

script_dir=$(cd "$(dirname "$0")"; pwd)
root_dir=$(cd "${script_dir}/../.."; pwd)
output_dir="${root_dir}/sct/${sct_ver}"

FPP='gfortran -E -cpp'
# FPP_FLAGS='-DHAVE_MPI'
FPP_FLAGS=''

OMNI='F_Front'
# OMNI_FLAGS="-M ${output_dir} -M ${root_dir}/mpi/3.0"
OMNI_FLAGS="-M ${output_dir}"

files='
sct.f90
'

mkdir -p "${output_dir}"
cd "${sct_dir}/src"

for file in ${files}; do
	${FPP} ${FPP_FLAGS} ${file} | ${OMNI} ${OMNI_FLAGS} >/dev/null
done
